version: 2.1

orbs:
  example:
    executors:
      default:
        docker:
          - image: circleci/node:erbium

jobs:
  build:
    executor: example/default
    steps:
      - checkout

workflows:
    build-and-release:
      jobs:
        - build:
            filters:
              tags:
                only: /.*/
